import { chart } from "../../../src/index.js";

import { createCarsTemporalBarLineValues } from "./reference-values.js";

const BAR_FILL = "#bfdbfe";
const LINE_STROKE = "#1d4ed8";
const AXIS_STROKE = "#334155";
const GRID_STROKE = "#e2e8f0";

export function createCarsTemporalBarLinePrimitives(rows) {
  const values = createCarsTemporalBarLineValues(rows);
  const { x: xAxis, y: yAxis } = values.axes;
  const xPositions = xAxis.ticks.map(tick => tick.position);
  const yPositions = yAxis.ticks.map(tick => tick.position);

  let program = chart()
    .editSemantic({ property: "dataset[cars].values", value: rows })
    .editSemantic({ property: "layer[bars].mark.type", value: "bar" })
    .editSemantic({ property: "layer[bars].data", value: "cars" })
    .editSemantic({ property: "layer[bars].coordinate", value: "main" })
    .editSemantic({ property: "layer[bars].encoding.x.field", value: "Year" })
    .editSemantic({ property: "layer[bars].encoding.x.fieldType", value: "temporal" })
    .editSemantic({ property: "layer[bars].encoding.x.scale", value: "x" })
    .editSemantic({ property: "layer[bars].encoding.y.field", value: "Acceleration" })
    .editSemantic({ property: "layer[bars].encoding.y.fieldType", value: "quantitative" })
    .editSemantic({ property: "layer[bars].encoding.y.aggregate", value: "mean" })
    .editSemantic({ property: "layer[bars].encoding.y.scale", value: "y" })
    .editSemantic({ property: "layer[trend].mark.type", value: "line" })
    .editSemantic({ property: "layer[trend].data", value: "cars" })
    .editSemantic({ property: "layer[trend].coordinate", value: "main" })
    .editSemantic({ property: "layer[trend].encoding.x.field", value: "Year" })
    .editSemantic({ property: "layer[trend].encoding.x.fieldType", value: "temporal" })
    .editSemantic({ property: "layer[trend].encoding.x.scale", value: "x" })
    .editSemantic({ property: "layer[trend].encoding.y.field", value: "Acceleration" })
    .editSemantic({ property: "layer[trend].encoding.y.fieldType", value: "quantitative" })
    .editSemantic({ property: "layer[trend].encoding.y.aggregate", value: "mean" })
    .editSemantic({ property: "layer[trend].encoding.y.scale", value: "y" })
    .editSemantic({ property: "scale[x].type", value: "time" })
    .editSemantic({ property: "scale[x].domain", value: "auto" })
    .editSemantic({ property: "scale[x].range", value: "auto" })
    .editSemantic({ property: "scale[x].nice", value: true })
    .editSemantic({ property: "scale[y].type", value: "linear" })
    .editSemantic({ property: "scale[y].domain", value: "auto" })
    .editSemantic({ property: "scale[y].range", value: "auto" })
    .editSemantic({ property: "scale[y].nice", value: true })
    .editSemantic({ property: "scale[y].zero", value: true })
    .editSemantic({ property: "coordinate[main].type", value: "cartesian" })
    .editSemantic({ property: "guide.axis.x.scale", value: "x" })
    .editSemantic({ property: "guide.axis.x.coordinate", value: "main" })
    .editSemantic({ property: "guide.axis.x.title", value: "Year" })
    .editSemantic({ property: "guide.axis.y.scale", value: "y" })
    .editSemantic({ property: "guide.axis.y.coordinate", value: "main" })
    .editSemantic({ property: "guide.axis.y.title", value: "Mean acceleration" })
    .editSemantic({ property: "guide.grid.horizontal.scale", value: "y" })
    .editSemantic({ property: "guide.grid.horizontal.coordinate", value: "main" })
    .editSemantic({ property: "title.text", value: values.title.text })
    .editSemantic({ property: "title.subtitle", value: values.title.subtitle })
    .createGraphics({ id: "canvas", type: "canvas" })
    .editGraphics({ target: "canvas", property: "width", value: values.width })
    .editGraphics({ target: "canvas", property: "height", value: values.height })
    .editGraphics({ target: "canvas", property: "background", value: "white" })
    .createGraphics({ id: "plot-main", type: "collection", parent: "canvas" })
    .createGraphics({
      id: "horizontalGridLines",
      type: "line",
      length: yPositions.length,
      parent: "plot-main"
    })
    .editGraphics({ target: "horizontalGridLines", property: "x1", value: values.bounds.x })
    .editGraphics({ target: "horizontalGridLines", property: "y1", value: yPositions })
    .editGraphics({
      target: "horizontalGridLines",
      property: "x2",
      value: values.bounds.x + values.bounds.width
    })
    .editGraphics({ target: "horizontalGridLines", property: "y2", value: yPositions })
    .editGraphics({ target: "horizontalGridLines", property: "stroke", value: GRID_STROKE })
    .editGraphics({ target: "horizontalGridLines", property: "strokeWidth", value: 1 })
    .editGraphics({ target: "horizontalGridLines", property: "strokeDash", value: yPositions.map(() => []) })
    .createGraphics({ id: "bars", type: "rect", length: values.bars.length, parent: "plot-main" })
    .editGraphics({ target: "bars", property: "x", value: values.bars.map(bar => bar.x) })
    .editGraphics({ target: "bars", property: "y", value: values.bars.map(bar => bar.y) })
    .editGraphics({ target: "bars", property: "width", value: values.bars.map(bar => bar.width) })
    .editGraphics({ target: "bars", property: "height", value: values.bars.map(bar => bar.height) })
    .editGraphics({ target: "bars", property: "fill", value: BAR_FILL })
    .editGraphics({ target: "bars", property: "stroke", value: "white" })
    .editGraphics({ target: "bars", property: "strokeWidth", value: 0.5 })
    .createGraphics({ id: "trend", type: "path", length: 1, parent: "plot-main" })
    .editGraphics({ target: "trend", property: "commands", value: [values.lineCommands] })
    .editGraphics({ target: "trend", property: "stroke", value: LINE_STROKE })
    .editGraphics({ target: "trend", property: "strokeWidth", value: 3 })
    .editGraphics({ target: "trend", property: "strokeDash", value: [[]] })
    .createGraphics({ id: "xAxisLine", type: "line", parent: "plot-main" })
    .editGraphics({ target: "xAxisLine", property: "x1", value: xAxis.line.x1 })
    .editGraphics({ target: "xAxisLine", property: "y1", value: xAxis.line.y1 })
    .editGraphics({ target: "xAxisLine", property: "x2", value: xAxis.line.x2 })
    .editGraphics({ target: "xAxisLine", property: "y2", value: xAxis.line.y2 })
    .editGraphics({ target: "xAxisLine", property: "stroke", value: AXIS_STROKE })
    .editGraphics({ target: "xAxisLine", property: "strokeWidth", value: 1 })
    .createGraphics({ id: "xAxisTicks", type: "line", length: xPositions.length, parent: "plot-main" })
    .editGraphics({ target: "xAxisTicks", property: "x1", value: xPositions })
    .editGraphics({ target: "xAxisTicks", property: "y1", value: xAxis.line.y1 })
    .editGraphics({ target: "xAxisTicks", property: "x2", value: xPositions })
    .editGraphics({ target: "xAxisTicks", property: "y2", value: xAxis.line.y1 + 6 })
    .editGraphics({ target: "xAxisTicks", property: "stroke", value: "#64748b" })
    .editGraphics({ target: "xAxisTicks", property: "strokeWidth", value: 1 })
    .createGraphics({ id: "xAxisLabels", type: "text", length: xPositions.length, parent: "plot-main" })
    .editGraphics({ target: "xAxisLabels", property: "x", value: xPositions })
    .editGraphics({ target: "xAxisLabels", property: "y", value: xAxis.line.y1 + 18 })
    .editGraphics({ target: "xAxisLabels", property: "text", value: xAxis.ticks.map(tick => tick.label) })
    .editGraphics({ target: "xAxisLabels", property: "fill", value: AXIS_STROKE })
    .editGraphics({ target: "xAxisLabels", property: "fontSize", value: 12 })
    .editGraphics({ target: "xAxisLabels", property: "fontFamily", value: "sans-serif" })
    .editGraphics({ target: "xAxisLabels", property: "fontWeight", value: "normal" })
    .editGraphics({ target: "xAxisLabels", property: "textAlign", value: "center" })
    .editGraphics({ target: "xAxisLabels", property: "textBaseline", value: "top" })
    .createGraphics({ id: "xAxisTitle", type: "text", parent: "plot-main" })
    .editGraphics({ target: "xAxisTitle", property: "x", value: xAxis.title.x })
    .editGraphics({ target: "xAxisTitle", property: "y", value: xAxis.title.y })
    .editGraphics({ target: "xAxisTitle", property: "text", value: xAxis.title.text })
    .editGraphics({ target: "xAxisTitle", property: "fill", value: AXIS_STROKE })
    .editGraphics({ target: "xAxisTitle", property: "fontSize", value: 13 })
    .editGraphics({ target: "xAxisTitle", property: "fontFamily", value: "sans-serif" })
    .editGraphics({ target: "xAxisTitle", property: "fontWeight", value: 600 })
    .editGraphics({ target: "xAxisTitle", property: "textAlign", value: "center" })
    .editGraphics({ target: "xAxisTitle", property: "textBaseline", value: "middle" })
    .editGraphics({ target: "xAxisTitle", property: "rotation", value: 0 })
    .createGraphics({ id: "yAxisLine", type: "line", parent: "plot-main" })
    .editGraphics({ target: "yAxisLine", property: "x1", value: yAxis.line.x1 })
    .editGraphics({ target: "yAxisLine", property: "y1", value: yAxis.line.y1 })
    .editGraphics({ target: "yAxisLine", property: "x2", value: yAxis.line.x2 })
    .editGraphics({ target: "yAxisLine", property: "y2", value: yAxis.line.y2 })
    .editGraphics({ target: "yAxisLine", property: "stroke", value: AXIS_STROKE })
    .editGraphics({ target: "yAxisLine", property: "strokeWidth", value: 1 })
    .createGraphics({ id: "yAxisTicks", type: "line", length: yPositions.length, parent: "plot-main" })
    .editGraphics({ target: "yAxisTicks", property: "x1", value: yAxis.line.x1 - 6 })
    .editGraphics({ target: "yAxisTicks", property: "y1", value: yPositions })
    .editGraphics({ target: "yAxisTicks", property: "x2", value: yAxis.line.x1 })
    .editGraphics({ target: "yAxisTicks", property: "y2", value: yPositions })
    .editGraphics({ target: "yAxisTicks", property: "stroke", value: "#64748b" })
    .editGraphics({ target: "yAxisTicks", property: "strokeWidth", value: 1 })
    .createGraphics({ id: "yAxisLabels", type: "text", length: yPositions.length, parent: "plot-main" })
    .editGraphics({ target: "yAxisLabels", property: "x", value: yAxis.line.x1 - 12 })
    .editGraphics({ target: "yAxisLabels", property: "y", value: yPositions })
    .editGraphics({ target: "yAxisLabels", property: "text", value: yAxis.ticks.map(tick => tick.label) })
    .editGraphics({ target: "yAxisLabels", property: "fill", value: AXIS_STROKE })
    .editGraphics({ target: "yAxisLabels", property: "fontSize", value: 12 })
    .editGraphics({ target: "yAxisLabels", property: "fontFamily", value: "sans-serif" })
    .editGraphics({ target: "yAxisLabels", property: "fontWeight", value: "normal" })
    .editGraphics({ target: "yAxisLabels", property: "textAlign", value: "right" })
    .editGraphics({ target: "yAxisLabels", property: "textBaseline", value: "middle" })
    .createGraphics({ id: "yAxisTitle", type: "text", parent: "plot-main" })
    .editGraphics({ target: "yAxisTitle", property: "x", value: yAxis.title.x })
    .editGraphics({ target: "yAxisTitle", property: "y", value: yAxis.title.y })
    .editGraphics({ target: "yAxisTitle", property: "text", value: yAxis.title.text })
    .editGraphics({ target: "yAxisTitle", property: "fill", value: AXIS_STROKE })
    .editGraphics({ target: "yAxisTitle", property: "fontSize", value: 13 })
    .editGraphics({ target: "yAxisTitle", property: "fontFamily", value: "sans-serif" })
    .editGraphics({ target: "yAxisTitle", property: "fontWeight", value: 600 })
    .editGraphics({ target: "yAxisTitle", property: "textAlign", value: "center" })
    .editGraphics({ target: "yAxisTitle", property: "textBaseline", value: "middle" })
    .editGraphics({ target: "yAxisTitle", property: "rotation", value: yAxis.title.rotation })
    .createGraphics({ id: "chartTitle", type: "text", parent: "canvas" })
    .editGraphics({ target: "chartTitle", property: "x", value: values.title.x })
    .editGraphics({ target: "chartTitle", property: "y", value: values.title.y })
    .editGraphics({ target: "chartTitle", property: "text", value: values.title.text })
    .editGraphics({ target: "chartTitle", property: "fill", value: AXIS_STROKE })
    .editGraphics({ target: "chartTitle", property: "fontSize", value: 18 })
    .editGraphics({ target: "chartTitle", property: "fontFamily", value: "sans-serif" })
    .editGraphics({ target: "chartTitle", property: "fontWeight", value: 700 })
    .editGraphics({ target: "chartTitle", property: "textAlign", value: "center" })
    .editGraphics({ target: "chartTitle", property: "textBaseline", value: "middle" })
    .createGraphics({ id: "chartSubtitle", type: "text", parent: "canvas" })
    .editGraphics({ target: "chartSubtitle", property: "x", value: values.title.x })
    .editGraphics({ target: "chartSubtitle", property: "y", value: values.title.subtitleY })
    .editGraphics({ target: "chartSubtitle", property: "text", value: values.title.subtitle })
    .editGraphics({ target: "chartSubtitle", property: "fill", value: "#64748b" })
    .editGraphics({ target: "chartSubtitle", property: "fontSize", value: 12 })
    .editGraphics({ target: "chartSubtitle", property: "fontFamily", value: "sans-serif" })
    .editGraphics({ target: "chartSubtitle", property: "fontWeight", value: "normal" })
    .editGraphics({ target: "chartSubtitle", property: "textAlign", value: "center" })
    .editGraphics({ target: "chartSubtitle", property: "textBaseline", value: "middle" });
  return program;
}
